name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Install Yandex CLI and configure docker auth
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          export PATH="$PATH:$HOME/yandex-cloud/bin"
          if [ -f "$HOME/yandex-cloud/bin/docker-credential-yc" ]; then
            sudo cp "$HOME/yandex-cloud/bin/docker-credential-yc" /usr/local/bin/
          fi
          if [ -f "$HOME/yandex-cloud/bin/yc" ]; then
            sudo cp "$HOME/yandex-cloud/bin/yc" /usr/local/bin/
          fi
          echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY_JSON }}' > key.json
          yc --version
          yc config set service-account-key key.json
          yc config set cloud-id b1g5bv1glb6q0iu7ujil
          yc config set folder-id b1gmgijkm3ugaq00n1le
          yc container registry configure-docker
          docker-credential-yc version
          cat ~/.docker/config.json
          rm key.json

      - name: Проверка валидности ключа сервисного аккаунта
        run: |
          echo '${{ secrets.YC_SERVICE_ACCOUNT_KEY_JSON }}' > key.json
          cat key.json | python3 -m json.tool || (echo "Секрет YC_SERVICE_ACCOUNT_KEY_JSON невалидный JSON!" && exit 1)

      - name: Проверка работы yc CLI и доступа к реестру
        run: |
          export PATH="$PATH:$HOME/yandex-cloud/bin"
          yc --version
          yc config list
          yc container registry list || (echo "Не удалось получить список реестров! Проверьте права сервисного аккаунта и cloud-id/folder-id." && exit 1)
          yc container image list --registry-id crp3t6gvtieggu7lip3q || (echo "Не удалось получить список образов в реестре! Проверьте права сервисного аккаунта и registry-id." && exit 1)

      - name: Проверка docker-credential-yc
        run: |
          docker-credential-yc version || (echo "docker-credential-yc не установлен или не работает!" && exit 1)

      # - name: Проверка docker login через credential helper
      #   run: |
      #     docker logout cr.yandex || true
      #     echo "Пробуем docker login через credential helper (yc)..."
      #     docker login cr.yandex --username oauth --password $(yc iam create-token) || (echo "docker login через credential helper не удался!" && exit 1)

      - name: Build Docker image
        run: |
          docker build -t cr.yandex/crp3t6gvtieggu7lip3q/app:${{ github.run_number }} .
          docker tag cr.yandex/crp3t6gvtieggu7lip3q/app:${{ github.run_number }} cr.yandex/crp3t6gvtieggu7lip3q/app:${{ github.run_number }}_latest

      - name: Push Docker image
        run: |
          docker push cr.yandex/crp3t6gvtieggu7lip3q/app:${{ github.run_number }}
          docker push cr.yandex/crp3t6gvtieggu7lip3q/app:${{ github.run_number }}_latest

      - name: Create release tag
        run: |
          git tag ${{ github.run_number }}
          git push origin ${{ github.run_number }}

      - name: Create release issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Release ${{ github.run_number }}`,
              body: `Release created\n\nVersion: ${{ github.run_number }}\nDate: ${new Date().toISOString()}`,
            })
